export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Home } from './Home/Home'
export { default as Skills } from './Skills/Skills'
export { default as Timeline } from './Timeline/Timeline'
export { default as Works } from './Works/Works'
export { default as Footer } from './Footer/Footer'