import logo from '../assets/logo.svg'
import javascript from '../assets/javascript.svg'
import react from '../assets/react.svg'
import redux from '../assets/redux.svg'
import tailwind from '../assets/tailwind.svg'
import typescript from '../assets/typescript.svg'
import bootstrap from '../assets/bootstrap.svg'
import css3 from '../assets/css3.svg'
import framerMotion from '../assets/framerMotion.svg'
import git from '../assets/git.svg'
import html5 from '../assets/html5.svg'
import sanity from '../assets/sanity.svg'
import sass from '../assets/sass.svg'
import materialUi from '../assets/materialUi.svg'
import figma from '../assets/figma.svg'
import vectorHeroLogos from '../assets/vectorHeroLogos.svg'
import avatar from '../assets/avatar.png'

export default { logo, javascript, react, redux, tailwind, typescript, bootstrap, css3, framerMotion, git, html5, sanity, sass, materialUi ,figma,vectorHeroLogos, avatar }